apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
   - name:  mysql-pass
     literals:
          - password=redhat
resources:
       - EFS-Provisioner.yml
       - RBAC.yml
       - Storage-Class.yml
       - Persistent-Volume-Claim-SQL.yml
       - Persistent-Volume-Claim-Joomla.yml
       - Deployment-MySQL.yml
       - Deployment-Joomla.yml