kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-storage-class"
spec:
  accessModes:
    - ReadWriteMany
  resources:
        requests:
             storage: 10Gi